spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3006/SpringBootDemoTest?useUnicode=true&characterEncoding=utf-8
    username: root
    password: password

logging:
  config: classpath:logback.xml

log4j:
  logger:
    jdbc:
      sqltiming: DEBUG
    package:
      path: TRACE
    java:
      sql:
        Connection: DEBUG
        Statement: DEBUG
        PreparedStatement: DEBUG
        ResultSet: DEBUG

server:
  port: 8080
  servlet:
    session:
      timeout: 38000
      persistent: true