spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SpringBootDemoTest?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: password

logging:
  config: classpath:logback.xml

log4j:
  logger:
    jdbc:
      sqltiming: INFO
    package:
      path: TRACE
    java:
      sql:
        Connection: INFO
        Statement: INFO
        PreparedStatement: INFO
        ResultSet: INFO

server:
  port: 8080
  servlet:
    session:
      timeout: 38000
      persistent: true